package me.parsell.glowstonedust.core;

import me.parsell.glowstonedust.common.GlowstoneWireBlock;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.block.Block;
import net.minecraft.block.Material;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class glowBlocks {
  public static final Block GLOWSTONEWIRE = new GlowstoneWireBlock(FabricBlockSettings.of(Material.SUPPORTED).breakInstantly().noCollision().luminance(8));

  public static void init(){
    Registry.register(Registry.BLOCK, new Identifier("glowstonedust", "glowstone_wire"), GLOWSTONEWIRE);
    
  }
}
