package me.parsell.glowstonedust;

import me.parsell.glowstonedust.core.glowBlocks;
import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap;
import net.fabricmc.fabric.api.client.rendering.v1.ColorProviderRegistry;
import net.minecraft.client.render.RenderLayer;

public class GlowstoneDustClient implements ClientModInitializer {
	@Override
	public void onInitializeClient(){
    BlockRenderLayerMap.INSTANCE.putBlock(glowBlocks.GLOWSTONEWIRE, RenderLayer.getCutout());
    ColorProviderRegistry.BLOCK.register((state, world, pos, tintIndex) -> {
			return 0xFFFF00;
		 }, glowBlocks.GLOWSTONEWIRE);
	}
}